version: "3.8"
services:
  app:
    build: .
    volumes:
      - ./src:/src
    ports:
      - 7000:7000
    image: app:clcdata
    container_name: cldata_container
    command: gunicorn --bind 0.0.0.0:7000 core.wsgi
    depends_on:
      - db
  db:
     image: postgres
     volumes:
       - ./data/db:/var/lib/postgresql/data
     env_file:
       - .env
     environment:
       - POSTGRES_DB=${POSTGRES_DB}
       - POSTGRES_USER=${POSTGRES_USER}
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     container_name: postgres_db
     ports:
       - "5433:5432"
