version: "3.8"
services:
  app:
    build: .
    volumes:
      - ./src:/src
    ports:
      - 7000:7000
    image: app:clcdata
    container_name: cldata_container
    command: gunicorn --bind 0.0.0.0:7000 core.wsgi
