# Generated by Django 3.2.7 on 2023-03-04 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults', models.CharField(max_length=6)),
                ('females', models.CharField(max_length=6)),
                ('males', models.CharField(max_length=6)),
                ('leaders', models.CharField(max_length=6)),
                ('children', models.CharField(max_length=6)),
                ('approved', models.BooleanField(default=False)),
                ('first_timers', models.CharField(max_length=6)),
                ('consistency', models.CharField(max_length=6)),
                ('date', models.DateField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
