# Generated by Django 3.2.7 on 2023-03-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total',
            field=models.CharField(default=2, max_length=6),
            preserve_default=False,
        ),
    ]
