# Generated by Django 3.2 on 2023-03-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='leaders_to_members',
            field=models.CharField(default='0:0', max_length=6),
        ),
        migrations.AddField(
            model_name='attendance',
            name='leaders_to_offering',
            field=models.CharField(default='0:0', max_length=6),
        ),
        migrations.AddField(
            model_name='attendance',
            name='members_to_offering',
            field=models.CharField(default='0:0', max_length=6),
        ),
    ]
