# Generated by Django 4.2.1 on 2023-06-07 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20230328_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='consistency',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='leaders_to_members',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='leaders_to_offering',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='members_to_offering',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='offering',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='tithe',
        ),
        migrations.CreateModel(
            name='WednesdayAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offering', models.CharField(max_length=11)),
                ('approved', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wednesday_attendance', to='dashboard.attendance')),
            ],
        ),
        migrations.CreateModel(
            name='SundayAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consistency', models.CharField(max_length=6)),
                ('offering', models.CharField(max_length=11)),
                ('tithe', models.CharField(max_length=11)),
                ('approved', models.BooleanField(default=False)),
                ('leaders_to_members', models.CharField(default='0:0', max_length=6)),
                ('leaders_to_offering', models.CharField(default='0:0', max_length=6)),
                ('members_to_offering', models.CharField(default='0:0', max_length=6)),
                ('date', models.DateField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sunday_attendance', to='dashboard.attendance')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialEventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('offering', models.CharField(max_length=11)),
                ('approved', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_event_attendance', to='dashboard.attendance')),
            ],
        ),
    ]
