# Generated by Django 4.2.1 on 2023-06-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_attendance_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('midweek_record', 'Can midweek record')],
            },
        ),
    ]
