# Generated by Django 4.2.1 on 2023-06-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_mypermission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyPermission',
            new_name='DashboardPermission',
        ),
        migrations.AlterModelOptions(
            name='dashboardpermission',
            options={'permissions': [('add_midweek_record', 'Can add midweek record')]},
        ),
    ]
