# Generated by Django 4.2.1 on 2023-07-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_mypermission_dashboardpermission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wednesdayattendance',
            name='attendance',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='adults',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='children',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='females',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='first_timers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='leaders',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='males',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sundayattendance',
            name='consistency',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sundayattendance',
            name='offering',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sundayattendance',
            name='tithe',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='attendance',
            table='attendance',
        ),
        migrations.AlterModelTable(
            name='sundayattendance',
            table='sunday_attendance',
        ),
        migrations.DeleteModel(
            name='SpecialEventAttendance',
        ),
        migrations.DeleteModel(
            name='WednesdayAttendance',
        ),
    ]
