# Generated by Django 3.2 on 2023-04-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_number',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
