# Generated by Django 3.2 on 2023-04-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230414_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_number',
            field=models.IntegerField(default=0, max_length=6),
        ),
    ]
