# Generated by Django 3.2 on 2023-04-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_otp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_number',
            field=models.IntegerField(default=0),
        ),
    ]
